env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:prettier/recommended
  - eslint:recommended
  - standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  "no-console": "error",
  "semi": ["error", "always"],
  "import/order": [ "error", {
    "groups": [ "builtin", "external", "internal", "parent", "sibling", "index", "object", "type" ],
    "newlines-between": "always",
  }],
  "comma-dangle": ["error", {
    "functions": "only-multiline",
    "objects": "only-multiline",
    "arrays": "only-multiline",
  }],
}
